export const post = {
  GET_POST_ROW_INITIATE: 'GET_POST_ROW_INITIATE',
  GET_POST_ROW_SUCCESS: 'GET_POST_ROW_SUCCESS',
  GET_POST_ROW_FAILURE: 'GET_POST_ROW_FAILURE',
  POST_ROW_INITIATE: 'POST_ROW_INITIATE',
  POST_ROW_SUCCESS: 'POST_ROW_SUCCESS',
  POST_ROW_FAILURE: 'POST_ROW_FAILURE',
  DELETE_ROW_INITIATE: 'DELETE_ROW_INITIATE',
  DELETE_ROW_SUCCESS: 'DELETE_ROW_SUCCESS',
  DELETE_ROW_FAILURE: 'DELETE_ROW_FAILURE',
}